name: Packages UI & Core (Pull Request) - Build

on:
  pull_request:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

jobs:
  packages-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build UI Library and Components
        run: yarn build
