name: Deploy to GitHub Repo

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build React App
        run: yarn build

      - name: Build Storybook
        run: yarn build-storybook

      - name: Move Storybook to dist
        run: |
          mkdir -p dist/storybook
          mv storybook-static/* dist/storybook/

      - name: Copy CNAME to dist
        run: |
          if [ -f CNAME ]; then
            cp CNAME dist/CNAME
          fi
        # Ensures that your custom domain (altrugenix.js.org) remains active

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # By default, this action publishes the contents of the publish_dir to the 'gh-pages' branch of THIS repository.
          # If you want to deploy to a DIFFERENT repository, you'll need to specify these arguments:
          external_repository: altrugenix/altrugenix.github.io
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
